[package]
name = "aptospay"
version = "1.0.0"
authors = []

[addresses]
owner = "0x243f2e34bf0f45fb71ff308228adc547b239ef11e18f65efe44f13162d90b606"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
